# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - frittteui

on:
  push:
    branches:
      - asratMinase
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://frittteregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_560a6deeb2b949f9841b1509b3dc97f2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8ba9d6e32c704b3d8e537e0e2449b6d4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: frittteregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_560a6deeb2b949f9841b1509b3dc97f2 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'frittteui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c4a31d8789264d8a92402c2714335af3 }}
        images: 'frittteregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_560a6deeb2b949f9841b1509b3dc97f2 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'